/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "github.com/mattgartman/k8s-testcrd/pkg/apis/coolresource/v1"
	scheme "github.com/mattgartman/k8s-testcrd/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CoolResourcesGetter has a method to return a CoolResourceInterface.
// A group's client should implement this interface.
type CoolResourcesGetter interface {
	CoolResources(namespace string) CoolResourceInterface
}

// CoolResourceInterface has methods to work with CoolResource resources.
type CoolResourceInterface interface {
	Create(*v1.CoolResource) (*v1.CoolResource, error)
	Update(*v1.CoolResource) (*v1.CoolResource, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.CoolResource, error)
	List(opts metav1.ListOptions) (*v1.CoolResourceList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CoolResource, err error)
	CoolResourceExpansion
}

// coolResources implements CoolResourceInterface
type coolResources struct {
	client rest.Interface
	ns     string
}

// newCoolResources returns a CoolResources
func newCoolResources(c *MattgartmanV1Client, namespace string) *coolResources {
	return &coolResources{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the coolResource, and returns the corresponding coolResource object, and an error if there is any.
func (c *coolResources) Get(name string, options metav1.GetOptions) (result *v1.CoolResource, err error) {
	result = &v1.CoolResource{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coolresources").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CoolResources that match those selectors.
func (c *coolResources) List(opts metav1.ListOptions) (result *v1.CoolResourceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CoolResourceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("coolresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested coolResources.
func (c *coolResources) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("coolresources").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a coolResource and creates it.  Returns the server's representation of the coolResource, and an error, if there is any.
func (c *coolResources) Create(coolResource *v1.CoolResource) (result *v1.CoolResource, err error) {
	result = &v1.CoolResource{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("coolresources").
		Body(coolResource).
		Do().
		Into(result)
	return
}

// Update takes the representation of a coolResource and updates it. Returns the server's representation of the coolResource, and an error, if there is any.
func (c *coolResources) Update(coolResource *v1.CoolResource) (result *v1.CoolResource, err error) {
	result = &v1.CoolResource{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("coolresources").
		Name(coolResource.Name).
		Body(coolResource).
		Do().
		Into(result)
	return
}

// Delete takes name of the coolResource and deletes it. Returns an error if one occurs.
func (c *coolResources) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coolresources").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *coolResources) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("coolresources").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched coolResource.
func (c *coolResources) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.CoolResource, err error) {
	result = &v1.CoolResource{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("coolresources").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
