/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	coolresourcev1 "github.com/mattgartman/k8s-testcrd/pkg/apis/coolresource/v1"
	versioned "github.com/mattgartman/k8s-testcrd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/mattgartman/k8s-testcrd/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/mattgartman/k8s-testcrd/pkg/client/listers/coolresource/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CoolResourceInformer provides access to a shared informer and lister for
// CoolResources.
type CoolResourceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.CoolResourceLister
}

type coolResourceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCoolResourceInformer constructs a new informer for CoolResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCoolResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCoolResourceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCoolResourceInformer constructs a new informer for CoolResource type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCoolResourceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattgartmanV1().CoolResources(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MattgartmanV1().CoolResources(namespace).Watch(options)
			},
		},
		&coolresourcev1.CoolResource{},
		resyncPeriod,
		indexers,
	)
}

func (f *coolResourceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCoolResourceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *coolResourceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&coolresourcev1.CoolResource{}, f.defaultInformer)
}

func (f *coolResourceInformer) Lister() v1.CoolResourceLister {
	return v1.NewCoolResourceLister(f.Informer().GetIndexer())
}
